[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.15"

[features]
resolution = true
skip-lint = false

[programs.localnet]
eros_marketplace_solana = "Ca8tTnDxUcXd1FKDaCc1x8m8faEU6NB3jfLhDNvrZK8a"

[programs.devnet]
eros_marketplace_solana = "Ca8tTnDxUcXd1FKDaCc1x8m8faEU6NB3jfLhDNvrZK8a"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
