[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
eros_marketplace_sale = "Ca8tTnDxUcXd1FKDaCc1x8m8faEU6NB3jfLhDNvrZK8a"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
